### ISSUE TITLE
암상인에 관하여

### ISSUE THREAD

**Issue by unitymind9** [kdeun1/d2-info#9]
안녕하세요!
구현하고 싶은 목록에 '암상인 (무기, 방어구 및 스텟의 경우 수동으로 입력할 듯. 각 지역 지도이미지로 표현 예정)' 항목을 써 두셨던데, 쥴이 오는 한국 시각 토요일 새벽 2시에 쥴(2190858386) 상인의 아이템 목록을 요청하면 쥴의 위치를 제외한 판매하는 장비 및 해당 장비의 스탯을 확인하실 수 있습니다 (수동으로 입력하지 않으셔도 돼요!)

**Comment by kdeun1** [comment]
안녕하세요. 많은 관심 감사합니다.
d2-info 사이트 리뉴얼 할 생각입니다. 
추후 암상인 부분도 연결할 예정입니다. 감사합니다.
쥴의 위치는 api로 못 가져오더라구요 해당 부분은 뭔가 수동으로 해야할 것 같은데
2년 전에 제가 사이트 개발, 운영했었을 당시에는 쥴이 판매하는 아이템 정보가 없었는데
지금 확인해보니 가져오도록 변경되었더라구요.
해당 사이트 개발 당시에는 2년 전 스펙을 알고 있던 상황이라 저런식으로 적었던 것 같아요.
리셋데가 사이트 잘 이용하고 있습니다.
소스는 오픈안하셨던데 혹시 API 사용하시면서 자동 업데이트 하시나요?

**Comment by unitymind9** [comment]
안녕하세요!
쥴 위치 관련해서 찾아봤었는데 번지가 의도적으로 공개하지 않고 있는 것 같아요.
소스 코드는 제 api 키, oauth2 관련 키들이 전부 공개되어있어서 따로 공개는 하지 않았고, API 사용하여 자동으로 매일 2시에 갱신됩니다(그래서 광고를 못달아요)
사이트 리뉴얼 기대하겠습니다!
